repos:
  - repo: https://github.com/icehuntmen/husky
    rev: v1.0.3
    hooks:
      - id: increment-patch-version
        name: Increment Patch Version
        entry: go run github.com/icehuntmen/husky@v1.0.3 patch
        language: golang
        pass_filenames: false
        always_run: true